#!/bin/bash
# =============================================================================
# SessionStart hook — rebuilds Home Assistant SSH access on every fresh
# container, because the container filesystem is wiped between sessions.
# Committed to GitHub (durable) + runs at startup (durable) + reads secrets
# from environment variables (durable). Nothing here depends on prior
# container state surviving.
#
# Result: `ssh homeassistant` works from the first moment of every session.
#
# Idempotent and secret-free — all secrets are read from the environment at
# runtime; none are stored in this file.
# =============================================================================
set -uo pipefail

log() { printf '[ha-ssh-setup] %s\n' "$*" >&2; }

# Only meaningful in the remote (Claude Code on the web) environment.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  log "not a remote session; skipping HA SSH setup"
  exit 0
fi

SSH_DIR="$HOME/.ssh"
mkdir -p "$SSH_DIR" && chmod 700 "$SSH_DIR"

# --- 1) openssh-client (ssh / ssh-keygen) ------------------------------------
if ! command -v ssh >/dev/null 2>&1; then
  log "installing openssh-client..."
  export DEBIAN_FRONTEND=noninteractive
  if apt-get update -qq >/dev/null 2>&1 && \
     apt-get install -y --no-install-recommends openssh-client >/dev/null 2>&1; then
    log "openssh-client installed"
  else
    log "WARN: openssh-client install failed"
  fi
else
  log "openssh-client present"
fi

# --- 2) cloudflared (client-side Cloudflare Access proxy) --------------------
# GitHub releases are out of scope in this environment, so install from
# Cloudflare's own apt repo instead of github.com.
CF_BIN="/usr/local/bin/cloudflared"
if ! command -v cloudflared >/dev/null 2>&1 && [ ! -x "$CF_BIN" ]; then
  log "installing cloudflared from pkg.cloudflare.com..."
  tmp="$(mktemp -d)"
  base="https://pkg.cloudflare.com/cloudflared"
  fn="$(curl -fsSL --max-time 60 "$base/dists/any/main/binary-amd64/Packages" 2>/dev/null \
        | awk '/^Filename:/{print $2; exit}')"
  if [ -n "${fn:-}" ] && curl -fsSL --max-time 180 -o "$tmp/cf.deb" "$base/$fn" 2>/dev/null; then
    if apt-get install -y "$tmp/cf.deb" >/dev/null 2>&1; then
      log "cloudflared installed"
    else
      # Fallback: extract the binary directly (no dependency resolution).
      dpkg-deb -x "$tmp/cf.deb" "$tmp/x" 2>/dev/null || true
      b="$(find "$tmp/x" -type f -name cloudflared 2>/dev/null | head -1)"
      [ -n "${b:-}" ] && install -m 0755 "$b" "$CF_BIN" 2>/dev/null \
        && log "cloudflared installed (extracted)" || log "WARN: cloudflared install failed"
    fi
  else
    log "WARN: could not download cloudflared"
  fi
  rm -rf "$tmp"
else
  log "cloudflared present"
fi

# --- 3) private key (with the required trailing-newline fix) ------------------
if [ -n "${HA_SSH_KEY_B64:-}" ]; then
  KEY="$SSH_DIR/ha_ssh_key"
  printf '%s' "$HA_SSH_KEY_B64" | base64 -d > "$KEY" 2>/dev/null || log "WARN: key decode failed"
  # Without a trailing newline OpenSSH rejects the key ("error in libcrypto").
  if [ -s "$KEY" ] && [ "$(tail -c1 "$KEY" | od -An -tx1 | tr -d ' ')" != "0a" ]; then
    printf '\n' >> "$KEY"
  fi
  chmod 600 "$KEY"
  if command -v ssh-keygen >/dev/null 2>&1 && ssh-keygen -y -f "$KEY" >/dev/null 2>&1; then
    log "SSH key ready ($(ssh-keygen -lf "$KEY" 2>/dev/null | awk '{print $2}'))"
  else
    log "WARN: SSH key did not parse"
  fi
else
  log "WARN: HA_SSH_KEY_B64 not set; skipping key setup"
fi

# --- 4) ProxyCommand wrapper (cloudflared + service token) -------------------
# ssh shells out to this; it bridges the SSH stream over the authenticated
# Cloudflare Access WebSocket. The MITM HTTPS proxy is stripped because
# cloudflared needs a direct TLS path to Cloudflare's edge on :443.
PROXY="$SSH_DIR/ha_cf_proxy.sh"
CF_PATH="$(command -v cloudflared 2>/dev/null || echo "$CF_BIN")"
cat > "$PROXY" <<PROXY_EOF
#!/bin/bash
# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand.
exec env -u HTTPS_PROXY -u HTTP_PROXY -u ALL_PROXY \\
         -u https_proxy -u http_proxy -u all_proxy \\
  "$CF_PATH" access ssh --hostname "\$1" \\
    --service-token-id "\${CF_ACCESS_CLIENT_ID:-}" \\
    --service-token-secret "\${CF_ACCESS_CLIENT_SECRET:-}"
PROXY_EOF
chmod 700 "$PROXY"

# --- 5) ssh config alias -> `ssh homeassistant` ------------------------------
HOST="${HA_SSH_HOST:-ssh.nmteaco.com}"
USER_NAME="${HA_SSH_USER:-root}"
[ -n "$USER_NAME" ] || USER_NAME="root"   # HA_SSH_USER may be set-but-empty
CFG="$SSH_DIR/config"
START="# >>> ha-ssh-setup >>>"
END="# <<< ha-ssh-setup <<<"
[ -f "$CFG" ] && sed -i "/$START/,/$END/d" "$CFG" 2>/dev/null   # drop prior managed block
{
  echo "$START"
  echo "Host homeassistant ha $HOST"
  echo "    HostName $HOST"
  echo "    User $USER_NAME"
  echo "    IdentityFile $SSH_DIR/ha_ssh_key"
  echo "    IdentitiesOnly yes"
  echo "    StrictHostKeyChecking accept-new"
  echo "    UserKnownHostsFile $SSH_DIR/known_hosts"
  echo "    ProxyCommand $PROXY %h"
  echo "    ConnectTimeout 50"
  echo "    ServerAliveInterval 15"
  echo "$END"
} >> "$CFG"
chmod 600 "$CFG"
log "ssh config ready — connect with: ssh homeassistant"

log "HA SSH setup complete"
exit 0
