#!/bin/bash
# =============================================================================
# SessionStart hook — rebuilds SSH access to BOTH boxes on every fresh
# container, because the container filesystem is wiped between sessions.
# Committed to GitHub (durable) + runs at startup (durable) + reads secrets
# from environment variables (durable). Nothing here depends on prior
# container state surviving.
#
# Result, from the first moment of every session:
#   ssh homeassistant   -> HAOS host (Terminal & SSH add-on, user root)
#   ssh aibox           -> the AI box "nmteacoaiserver" (Chloe), user nmteaco
#
# Both hosts sit behind Cloudflare Access, each with its OWN service token:
#   HA host  : CF_ACCESS_CLIENT_ID_HA     / CF_ACCESS_CLIENT_SECRET_HA
#   AI box   : CF_ACCESS_CLIENT_ID_AI_BOX / CF_ACCESS_CLIENT_SECRET_AI_BOX
# (The old UNSUFFIXED CF_ACCESS_CLIENT_ID/SECRET are gone/empty — using them
#  yields Cloudflare Access 403, which cloudflared reports as the misleading
#  "websocket: bad handshake". This was a real time-sink; do not reintroduce.)
#
# Both hosts authenticate SSH with the SAME key (HA_SSH_KEY_B64).
#
# Idempotent and secret-free — all secrets are read from the environment at
# runtime; none are stored in this file.
# =============================================================================
set -uo pipefail

log() { printf '[ha-ssh-setup] %s\n' "$*" >&2; }

# Only meaningful in the remote (Claude Code on the web) environment.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  log "not a remote session; skipping SSH setup"
  exit 0
fi

SSH_DIR="$HOME/.ssh"
mkdir -p "$SSH_DIR" && chmod 700 "$SSH_DIR"

# --- 1) openssh-client (ssh / ssh-keygen) ------------------------------------
if ! command -v ssh >/dev/null 2>&1; then
  log "installing openssh-client..."
  export DEBIAN_FRONTEND=noninteractive
  if apt-get update -qq >/dev/null 2>&1 && \
     apt-get install -y --no-install-recommends openssh-client >/dev/null 2>&1; then
    log "openssh-client installed"
  else
    log "WARN: openssh-client install failed"
  fi
else
  log "openssh-client present"
fi

# --- 2) cloudflared (client-side Cloudflare Access proxy) --------------------
# GitHub releases are out of scope in this environment, so install from
# Cloudflare's own apt repo instead of github.com.
CF_BIN="/usr/local/bin/cloudflared"
if ! command -v cloudflared >/dev/null 2>&1 && [ ! -x "$CF_BIN" ]; then
  log "installing cloudflared from pkg.cloudflare.com..."
  tmp="$(mktemp -d)"
  base="https://pkg.cloudflare.com/cloudflared"
  fn="$(curl -fsSL --max-time 60 "$base/dists/any/main/binary-amd64/Packages" 2>/dev/null \
        | awk '/^Filename:/{print $2; exit}')"
  if [ -n "${fn:-}" ] && curl -fsSL --max-time 180 -o "$tmp/cf.deb" "$base/$fn" 2>/dev/null; then
    if apt-get install -y "$tmp/cf.deb" >/dev/null 2>&1; then
      log "cloudflared installed"
    else
      # Fallback: extract the binary directly (no dependency resolution).
      dpkg-deb -x "$tmp/cf.deb" "$tmp/x" 2>/dev/null || true
      b="$(find "$tmp/x" -type f -name cloudflared 2>/dev/null | head -1)"
      [ -n "${b:-}" ] && install -m 0755 "$b" "$CF_BIN" 2>/dev/null \
        && log "cloudflared installed (extracted)" || log "WARN: cloudflared install failed"
    fi
  else
    log "WARN: could not download cloudflared"
  fi
  rm -rf "$tmp"
else
  log "cloudflared present"
fi

# --- 3) private key (with the required trailing-newline fix) ------------------
# One key authorizes BOTH hosts (root@HA and nmteaco@aibox).
KEY="$SSH_DIR/ha_ssh_key"
if [ -n "${HA_SSH_KEY_B64:-}" ]; then
  printf '%s' "$HA_SSH_KEY_B64" | base64 -d > "$KEY" 2>/dev/null || log "WARN: key decode failed"
  # Without a trailing newline OpenSSH rejects the key ("error in libcrypto").
  if [ -s "$KEY" ] && [ "$(tail -c1 "$KEY" | od -An -tx1 | tr -d ' ')" != "0a" ]; then
    printf '\n' >> "$KEY"
  fi
  chmod 600 "$KEY"
  if command -v ssh-keygen >/dev/null 2>&1 && ssh-keygen -y -f "$KEY" >/dev/null 2>&1; then
    log "SSH key ready ($(ssh-keygen -lf "$KEY" 2>/dev/null | awk '{print $2}'))"
  else
    log "WARN: SSH key did not parse"
  fi
else
  log "WARN: HA_SSH_KEY_B64 not set; skipping key setup"
fi

# --- 4) ProxyCommand wrapper (cloudflared + the RIGHT service token) ----------
# ssh shells out to this with the target hostname (%h); the wrapper picks the
# matching Cloudflare Access service token and bridges the SSH stream over the
# authenticated Access WebSocket. The MITM HTTPS proxy is stripped because
# cloudflared needs a direct TLS path to Cloudflare's edge on :443.
PROXY="$SSH_DIR/ha_cf_proxy.sh"
CF_PATH="$(command -v cloudflared 2>/dev/null || echo "$CF_BIN")"
HA_HOST="${HA_SSH_HOST:-ssh.nmteaco.com}"
AIBOX_HOST="${AI_BOX_SSH_HOST:-ssh-ai.nmteaco.com}"
cat > "$PROXY" <<PROXY_EOF
#!/bin/bash
# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand.
# Picks the Cloudflare Access service token by target hostname.
host="\$1"
case "\$host" in
  "$AIBOX_HOST")
    id="\${CF_ACCESS_CLIENT_ID_AI_BOX:-}"; sec="\${CF_ACCESS_CLIENT_SECRET_AI_BOX:-}";;
  *)
    id="\${CF_ACCESS_CLIENT_ID_HA:-\${CF_ACCESS_CLIENT_ID:-}}"
    sec="\${CF_ACCESS_CLIENT_SECRET_HA:-\${CF_ACCESS_CLIENT_SECRET:-}}";;
esac
exec env -u HTTPS_PROXY -u HTTP_PROXY -u ALL_PROXY \\
         -u https_proxy -u http_proxy -u all_proxy \\
  "$CF_PATH" access ssh --hostname "\$host" \\
    --service-token-id "\$id" \\
    --service-token-secret "\$sec"
PROXY_EOF
chmod 700 "$PROXY"

# --- 5) ssh config aliases ---------------------------------------------------
HA_USER="${HA_SSH_USER:-root}"
[ -n "$HA_USER" ] || HA_USER="root"          # HA_SSH_USER may be set-but-empty
AIBOX_USER="${AI_BOX_SSH_USER:-nmteaco}"      # AI box login user
[ -n "$AIBOX_USER" ] || AIBOX_USER="nmteaco"
CFG="$SSH_DIR/config"
START="# >>> ha-ssh-setup >>>"
END="# <<< ha-ssh-setup <<<"
[ -f "$CFG" ] && sed -i "/$START/,/$END/d" "$CFG" 2>/dev/null   # drop prior managed block
{
  echo "$START"
  echo "Host homeassistant ha $HA_HOST"
  echo "    HostName $HA_HOST"
  echo "    User $HA_USER"
  echo "    IdentityFile $KEY"
  echo "    IdentitiesOnly yes"
  echo "    StrictHostKeyChecking accept-new"
  echo "    UserKnownHostsFile $SSH_DIR/known_hosts"
  echo "    ProxyCommand $PROXY %h"
  echo "    ConnectTimeout 50"
  echo "    ServerAliveInterval 15"
  echo ""
  echo "Host aibox chloe ai-box $AIBOX_HOST"
  echo "    HostName $AIBOX_HOST"
  echo "    User $AIBOX_USER"
  echo "    IdentityFile $KEY"
  echo "    IdentitiesOnly yes"
  echo "    StrictHostKeyChecking accept-new"
  echo "    UserKnownHostsFile $SSH_DIR/known_hosts"
  echo "    ProxyCommand $PROXY %h"
  echo "    ConnectTimeout 50"
  echo "    ServerAliveInterval 15"
  echo "$END"
} >> "$CFG"
chmod 600 "$CFG"
log "ssh config ready — connect with: ssh homeassistant   |   ssh aibox"

log "SSH setup complete"
exit 0
